Fixed reports to work with latest DB
Capping-CPCA/Web-App pull request #118
Opened 2017-11-09 20:16 UTC by stickzman

Monthly and custom reports will not work without this fix!

Sidenote: Curriculum selection in custom reports works, but it pulls it from the database, so if there is no entries present, there will be nothing to select.

2017-11-09 21:00 UTC, ghost requested changes

2017-11-09 21:00 UTC, evanmena commented on views/reports/custom_reports_table.php
> +		$id = $currs[$i];
`$id = $currs[$i];` here is unnecessary but gives a bit of self documentation. Instead, add a comment on line 82 explaining what this block of code is doing (getting all of the curricula ids into a comma separated list for pgsql)

2017-11-09 23:33 UTC, blackjack26 approved these changes

2017-11-10 00:23 UTC, ghost approved these changes

2017-11-10 00:59 UTC, merged