Added reports UI pages and routes
Capping-CPCA/Web-App pull request #52
Opened 2017-10-17 19:32 UTC by stickzman

Added reports pages. Fixes #31

2017-10-17 19:46 UTC, evanmena commented
Looks like we need to add a standard comment header. The format is in the [wiki](https://github.com/Capping-CPCA/Web-App/wiki/Adding-New-Pages)

2017-10-17 19:47 UTC, ghost requested changes
Each new page needs a header comment, standard found in the wiki

2017-10-17 20:03 UTC, blackjack26 requested changes

2017-10-17 20:03 UTC, blackjack26 commented on routes.php
> +$router->add('/custom_reports_table.php', 'reports/custom_reports_table.php', 'Custom Report');
Change the URL from `/custom_reports_table.php` to `/custom-reports-table`.

2017-10-17 20:03 UTC, blackjack26 commented on views/reports/custom_reports.php
> +                    <a href="custom_reports_table.php" class="btn btn-primary">Generate Report</a>
Change `custom_reports_table.php` to `/custom-reports-table`. All page navigation is through routes.

2017-10-17 20:03 UTC, blackjack26 commented on views/reports/custom_reports.php
> +                    <a href="custom_reports_table.php" class="btn btn-primary">Generate Report</a>
Also don't use the class `btn-primary`, use `cpca` instead.

2017-10-17 20:03 UTC, blackjack26 commented on views/reports/half_year.php
> +                    <a class="btn btn-primary btn-large" href="#">Generate Report</a>
`cpca` instead of `btn-primary`

2017-10-17 20:03 UTC, blackjack26 commented on views/reports/monthly_report.php
> +                    <a class="btn btn-primary btn-large" href="#">Generate Report</a>
`cpca` instead of `btn-primary`

2017-10-17 20:03 UTC, blackjack26 commented on views/reports/half_year.php
> +        Semi-Annual 2017</h3>
Tag mismatch. This tag is opened with an `<h1>` but closed with an `</h3>`

2017-10-17 20:03 UTC, blackjack26 commented on views/reports/quarterly.php
> +        Q1 2017</h3>
Tag mismatch. This tag is opened with an `<h1>` but closed with an `</h3>`.

2017-10-17 20:03 UTC, blackjack26 commented on views/reports/custom_reports.php
> +﻿<?php
This file is saved using the encoding `UTF-8-BOM` which could have occurred if you were using notepad to write the file. Change this file encoding to `UTF-8` (the `UTF-8-BOM` adds a whitespace to the top of this page)

2017-10-17 20:03 UTC, blackjack26 commented on views/reports/custom_reports_table.php
> +﻿<?php
This file is saved using the encoding `UTF-8-BOM` which could have occurred if you were using notepad to write the file. Change this file encoding to `UTF-8` (the `UTF-8-BOM` adds a whitespace to the top of this page)

2017-10-17 20:04 UTC, blackjack26 commented
Also I would suggest adding `table-striped` to all the tables. Makes them easier to read / look at.

2017-10-17 23:43 UTC, ghost approved these changes

2017-10-17 23:45 UTC, blackjack26 commented
Looks good to me. One last thing, I'll be releasing this merge with a version tag of `0.1.4`. Since it's only the interface part it'll be a small version release. Once the actual functionality is put it, it'll be a larger version update. So in your comments put:
```php
/**
 * @version 0.1.4
 * @since 0.1.4
 */
```

2017-10-18 14:01 UTC, blackjack26 approved these changes

2017-10-18 14:02 UTC, merged